services:
  postgres-coffee:
    image: postgres:15-alpine
    container_name: kopi_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kopi
    ports:
      - "5438:5432"
    volumes:
      - kopi_data:/var/lib/postgresql/data

volumes:
  kopi_data: