services:
  postgres-coffee:
    image: postgres:15-alpine
    container_name: toko_kopi_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: toko_kopi
    ports:
      - "5433:5433"
    volumes:
      - toko_kopi_data:/var/lib/postgresql/data

volumes:
  toko_kopi_data: